_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/main.py
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
agent_type:
    value: drnd_ppo
batch_size:
    value: 64
buffer_size:
    value: 100000
capture_video:
    value: true
env_id:
    value: CartPole-v1
exp_name:
    value: main
num_envs:
    value: 1
save_model:
    value: false
seed:
    value: 42
total_timesteps:
    value: 100000
track:
    value: true
wandb_project_name:
    value: nanodqn
