wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.17
    cli_version: 0.19.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747922872
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 13
      - 14
      - 16
      - 17
      - 23
      - 37
      4: 3.10.17
      5: 0.19.11
      8:
      - 5
      - 9
      10:
      - 3
      - 20
      13: darwin-arm64
env_id:
  desc: null
  value: Acrobot-v1
env_name:
  desc: null
  value: Acrobot-v1
exp_name:
  desc: null
  value: rnd_experiment
num_envs:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 200000
learning_rate:
  desc: null
  value: 0.0001
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 1.0
buffer_size:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 16
target_network_frequency:
  desc: null
  value: 500
seed:
  desc: null
  value: 2025
seeds:
  desc: null
  value:
  - 42
  - 1337
  - 2025
  - 7
  - 99
capture_video:
  desc: null
  value: false
agent_type:
  desc: null
  value: epsilon_greedy
wandb_project_name:
  desc: null
  value: EpistemicUncertaintyRL
save_model:
  desc: null
  value: false
track:
  desc: null
  value: true
predictor_hidden_dim:
  desc: null
  value: 32
target_hidden_dim:
  desc: null
  value: 32
intrinsic_coef:
  desc: null
  value: 1.0
extrinsic_coef:
  desc: null
  value: 2
predictor_update_freq:
  desc: null
  value: 4
epsilon:
  desc: null
  value: 0.5
epsilon_final:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.9
train_frequency:
  desc: null
  value: 10
learning_starts:
  desc: null
  value: 10000
hidden_dim:
  desc: null
  value: 64
