env_id: "DeepSea-bsuite"

# Environment settings
num_envs: 1
env_size: 10
total_timesteps: 250000
seed: 2025

# Agent settings
agent_type: "epsilon_greedy"

# Exploration settings
epsilon: 1.0
epsilon_final: 0.1
exploration_fraction: 0.2

# Optimization hyperparameters
learning_rate: 0.001
gamma: 0.999
tau: 1.0
buffer_size: 50000
batch_size: 16
target_network_frequency: 200
train_start: 1000
train_frequency: 10

# Logging & tracking
track: true
capture_video: false
save_model: false
wandb_project_name: "Add name"
