env_id: "CartPole-v1"
env_name: "CartPole-v1"
exp_name: "drnd_ppo_experiment"
num_envs: 1
seed: 42
track: true
capture_video: true
save_model: false
wandb_project_name: "nanodqn"
agent_type: drnd_ppo

# Training parameters
total_timesteps: 100000
learning_rate: 0.0003
gamma: 0.99
buffer_size: 100000
batch_size: 64
exploration_fraction: 0.1
exploration_final_eps: 0.01

# DRND-PPO-specific parameters
predictor_hidden_dim: 512
target_hidden_dim: 512
intrinsic_reward_scale: 1.0
num_target_networks: 5
alpha: 0.95
update_epochs: 4
update_proportion: 0.25

# PPO-specific parameters
ppo_epochs: 4
ppo_batch_size: 64
clip_eps: 0.2
ent_coef: 0.01
max_grad_norm: 0.5
gae_lambda: 0.95
