# configs/epsilon_greedy.yaml


# General experiment information
agent_type: epsilon_greedy
env_name: CartPole-v1
seed: 42
track: true
capture_video: true
save_model: false
wandb_project_name: "nanodqn"
exp_name: "epsilon_greedy_experiment"

# Exploration settings
epsilon_start: 1.0
epsilon_final: 0.01
epsilon_decay: 10000
exploration_fraction: 0.5
learning_starts: 10000

# Training parameters
total_timesteps: 100000
batch_size: 64
buffer_size: 100000
gamma: 0.99
tau: 1.0
target_network_frequency: 500
train_freq: 4

# Algorithm-specific hyperparameters
learning_rate: 0.001
train_start: 1000
train_frequency: 10

# Environment settings
num_envs: 1
