# configs/epsilon_greedy.yaml


# General experiment information
agent_type: epsilon_greedy
env_id: "Acrobot-v1"
env_name: Acrobot-v1
seed: 42
track: true
capture_video: false
save_model: false
wandb_project_name: "EpistemicUncertaintyRL"
exp_name: "epsilon_greedy_experiment"

# Exploration settings
epsilon: 1.0
epsilon_final: 0.0001
exploration_fraction: 0.03

# Training parameters
total_timesteps: 300000
batch_size: 64
buffer_size: 50000
gamma: 0.99
tau: 1.0
target_network_frequency: 50
train_freq: 1

# Algorithm-specific hyperparameters
learning_rate: 0.001
train_start: 1000
train_frequency: 10

# Environment settings
num_envs: 1
