# configs/rnd.yaml

env_id: "ALE/MontezumaRevenge-v5"
env_name: ALE/MontezumaRevenge-v5
exp_name: "rnd_experiment"
num_envs: 1
total_timesteps: 12500000
learning_rate: 0.0001
gamma: 0.99
tau: 1.0
buffer_size: 10000
batch_size: 64
target_network_frequency: 500
seed: 7
seeds: [42, 1337, 2025, 7, 99]
capture_video: false
agent_type: rnd
wandb_project_name: "EpistemicUncertaintyRL"
save_model: false
track: true
predictor_hidden_dim: 512
target_hidden_dim: 512
intrinsic_coef: 1.0
extrinsic_coef: 2.0
predictor_update_freq: 4
temperature: 1.0

epsilon: 1.0
epsilon_final: 0
exploration_fraction: 0.9
train_frequency: 10
learning_starts: 10000
