# configs/rnd.yaml

env_id: "ALE/MontezumaRevenge-v5"
env_name: ALE/MontezumaRevenge-v5
exp_name: "rnd_experiment"
num_envs: 1
total_timesteps: 10000000
learning_rate: 0.0001
gamma: 0.99
tau: 1.0
buffer_size: 10000
batch_size: 16
target_network_frequency: 500
seed: 42
capture_video: true
agent_type: rnd
wandb_project_name: "EpistemicUncertaintyRL"
save_model: false
track: true
predictor_hidden_dim: 32
target_hidden_dim: 32
intrinsic_coef: 1.0
extrinsic_coef: 2.0
predictor_update_freq: 1

epsilon: 1.0
epsilon_final: 0.05
exploration_fraction: 0.9
train_frequency: 10
learning_starts: 10000
