method: bayes
program: main.py
metric:
  name: charts/episodic_return
  goal: maximize

parameters:
  extrinsic_coef:
    values: [0.25, 1.0, 2.0]
  hidden_dim:
    values: [ 32, 64 ]
  predictor_update_freq:
    values: [2, 4]

