method: grid
program: main_gymnax.py
metric:
  name: charts/episodic_return
  goal: maximize

parameters:
  seed:
    values: [ 42, 1337, 2025, 7, 99 ]
  extrinsic_coef:
    values: [ 0.5, 1.0, 2.0 ]
  hidden_dim:
    values: [ 16, 32 ]
  temperature:
    values: [ 0.2, 0.5, 1.0 ]
  env_size:
    values: [8, 10, 12]

