method: bayes
program: main.py
metric:
  name: eval/average_reward
  goal: maximize

parameters:
  batch_size:
    values: [32, 64]

  learning_rate:
    min: 0.00005
    max: 0.001

  gamma:
    values: [0.99, 0.995]

  extrinsic_coef:
    values: [0.25, 0.5, 1.0, 2.0]

  hidden_dim:
    values: [ 64, 128]

  predictor_update_freq:
    values: [2, 4]

